# Solana Yellowstone gRPC 配置

# gRPC 端点地址
grpc_endpoint = "https://solana-yellowstone-grpc.publicnode.com:443"
# Redis 配置
redis_url = "redis://127.0.0.1:6379/"
 
# 要监听的 Solana 地址列表
monitored_addresses = [
    "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
]

# PumpFun 程序 ID
pump_program_id = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"

# PumpFun IDL 文件路径
pump_idl_path = "idls/pump_0.1.0.json"
token_idl_path = "idls/token_program_idl.json"

# IDL 文件路径（可选）
# idl_path = "idls/your_program.json" 

# 功能开关配置
[features]
# 是否启用简单的交易监控 (类似 stream_and_parse_pump_transactions)
basic_transaction_monitoring = true
# 是否启用详细的买卖事件检测和分析 (类似 stream_transaction_detect_buy_sell_event)
advanced_event_detection = true
# 是否启用Token交易监控
token_transaction_monitoring = true
# 是否启用PumpFun绑定曲线账户监控 (类似 stream_and_parse_pumpfun_account_updates)
account_monitoring = true
# 是否将GRPC解析的数据缓存到内存中 (每10秒清理一次)
enable_cache = true
# 是否记录交易到文件
log_to_file = true
# 日志文件路径
log_file_path = "logs/transactions.log" 

# Redis 配置 # This line will be effectively removed by moving redis_url up
# redis_url = "redis://127.0.0.1/" # This line will be effectively removed by moving redis_url up 